### ISSUE TITLE
Styling Issue with Date in Chrome

### ISSUE THREAD

**Issue by harshay97** [hardy1334/ip_proj-#1]
In Chrome there is some styling issue with 27th April date,its something with alignment issue.

![Screenshot from 2019-04-21 12-18-48](https://user-images.githubusercontent.com/44117346/56466478-60fe5800-6430-11e9-8d1d-143449a26cab.png)

**Comment by harshay97** [comment]
@hardy1334 I will like to work on it

**Comment by hardy1334** [comment]
Sure go for It
